# tasks file for kibana
---
  - name: Upload .tar.gz file containing binaries from local storage
    copy:
      src: "{{ kb_distr_name }}"
      dest: "/tmp/kibana-{{ kb_distr_name }}"
      mode: 0755
    register: download_kb_local_binaries
    until: download_kb_local_binaries is succeeded
#    when: elk_distr_type == 'local'
  - name: Create directrory for Kibana
    file:
      state: directory
      path: "{{ kb_home }}"
    tags: kibana
  - name: Extract Kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kb_version }}-linux-x86_64.tar.gz"
      dest: "{{ kb_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ kb_home }}/bin/kibana"
    tags:
      - skip_ansible_lint
      - kibana
  - name: Configure Kibana
    become: true
    template:
      src: kibana.yml.j2
      dest: "{{ kb_home }}/config/kibana.yml"
      mode: 0644
    tags: kibana
