---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        kb_version: "{{ kb_distr_name.split('-')[:1] | join('-') }}"
        kb_home: "/opt/kibana/{{ kb_version }}"
#        elk_distr_type: local
        kb_distr_name: "{{ kibana[710] }}"
#        jdk_folder: "{{ jdk_distr_name.split('-')[:2] | join('-')  }}" 
verifier:
  name: ansible
